name: Unittest and Coverage

on:
  push:
  release:
    types: [published]

jobs:
  unittest:
    runs-on: ubuntu-latest
    env:
      NUMBA_DISABLE_JIT: 1
    steps:
      - uses: actions/checkout@v2
      # Setup miniconda nd build env
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge
          activate-environment: xcube-resampling
          environment-file: environment.yml
      # Install xcube-resampling
      - name: install
        shell: bash -l {0}
        run: |
          conda info
          conda list
          python setup.py develop
      # Run xcube-resampling's unittests
      - name: unit-tests
        shell: bash -l {0}
        run: |
          pip install pytest pytest-cov
          pytest --cov=xcube_resampling/ --cov-report=xml
      - uses: codecov/codecov-action@v1
        with:
          verbose: true # optional (default = false)
